# Generated by Django 5.1.6 on 2025-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/images/b.jpg', upload_to='banners/')),
                ('title', models.CharField(default='Welcome to Pulari Australia', max_length=255)),
                ('subtitle', models.CharField(default='Building a Stronger Community Together', max_length=255)),
            ],
        ),
    ]
