# Generated by Django 5.1.6 on 2025-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Pulari', max_length=255)),
                ('description', models.TextField(default='Pulari is a registered Non-Profit Organization under the Consumer Affairs of Victoria, Australia.')),
                ('image', models.ImageField(default=' static/images/about.jpg', upload_to='about_us/')),
                ('points', models.TextField(default='Discover and nurture community talents.|Promote Indian values, culture, and arts to future generations.|Organize events with local and international talents.|Raise funds for charitable causes.', help_text="Enter bullet points separated by '|' (pipe symbol)")),
                ('extra_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
