# Generated by Django 5.1.6 on 2025-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='static/images/about.jpg', upload_to='about_us/'),
        ),
    ]
